FROM node:18.19.0

# ARG PORT
ARG PORT
ARG MONGO
ARG JWT_SECRET
ARG JWT_LIFETIME
ARG BASE_URL

ARG CHAPA_LIVE_KEY
ARG CHAPA_LIVE_SECRET
ARG SANTIM_PAY_PRIVATE_KEY
ARG SANTIM_PAY_PUBLIC_KEY
ARG SANTIM_PAY_MERCHANT_ID
ARG SANTIM_PAY_TOKEN
ARG CLIENT_BASE_URL


ARG EMAIL_PASSWORD
ARG EMAIL_USER
ARG BASE_URL1


ENV PORT=$PORT
ENV MONGO=$MONGO
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_LIFETIME=$JWT_LIFETIME
ENV BASE_URL=$BASE_URL

ENV EMAIL_PASSWORD=$EMAIL_PASSWORD
ENV EMAIL_USER=$EMAIL_USER
ENV BASE_URL1=$BASE_URL1

ENV CHAPA_LIVE_KEY=$CHAPA_LIVE_KEY
ENV CHAPA_LIVE_SECRET=$CHAPA_LIVE_SECRET
ENV SANTIM_PAY_PRIVATE_KEY=$SANTIM_PAY_PRIVATE_KEY
ENV SANTIM_PAY_PUBLIC_KEY=$SANTIM_PAY_PUBLIC_KEY
ENV SANTIM_PAY_MERCHANT_ID=$SANTIM_PAY_MERCHANT_ID
ENV SANTIM_PAY_TOKEN=$SANTIM_PAY_TOKEN
ENV CLIENT_BASE_URL=$CLIENT_BASE_URL


# ENV MONGODB_URL=$MONGODB_URL


ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install 

COPY . .
CMD  npm run start

EXPOSE 2122